[default.extend-identifiers]
# https://github.com/crate-ci/typos/issues/436
BRE = "BRE"

[default.extend-words]
# completions-core/abook
informat = "informat"
# completions-core/ri
ane = "ane"
# completions-core/reportbug
buildd = "buildd"
# completions-core/tar
caf = "caf"
# completions-core/chage, test/t/Makefile.am, test/t/test_chage.py,
# test/test-cmd-list.txt
chage = "chage"
# test/t/test_ccache.py
clea = "clea"
# test/t/test_pylint_3.py
clien = "clien"
# completions-core/openssl
ede = "ede"
# completions-core/patch
fior = "fior"
# completions-core/make
fo = "fo"
# completions-fallback/.gitignore, completions-fallback/Makefile.am,
# completions-fallback/_hexdump, completions-core/gnome-screenshot,
# completions-core/mii-diag, completions-core/mii-tool, completions-core/qemu,
hd = "hd"
# test/t/test_ccache.py
hel = "hel"
# completions-core/bts
helo = "helo"
# completions-core/ip
iif = "iif"
# completions-core/tcpdump
inout = "inout"
# test/t/unit/test_unit_expand_glob.py
ket = "ket"
# completions-core/isql
Lins = "Lins"
# completions-core/hcitool, completions-core/ip
lst = "lst"
# completions-core/tshark, test/t/test_screen.py
nd = "nd"
# bash_completion
odf = "odf"
# completions-core/ip
oif = "oif"
# completions-core/mplayer
oly = "oly"
# test/t/unit/test_unit_find_unique_completion_pair.py
ot = "ot"
# completions-core/modinfo
parm = "parm"
# bash_completion, completions-core/eog, completions-core/gnome-screenshot,
# test/t/test_nmap.py
pn = "pn"
# completions-core/wget
referer = "referer"
# completions-core/_mount.linux, completions-core/tune2fs, test/t/test_curl.py,
# test/t/unit/test_unit_find_unique_completion_pair.py
ro = "ro"
# completions-core/ps
ser = "ser"

[files]
extend-exclude = ["CHANGELOG.md"]
