[global]
exclude = [
  "CHANGELOG.md",
]

[emphasis-style]
style = "underscore" # opinionated

[line-length]
code-blocks = false

[no-inline-html]
allowed-elements = [
  "kbd",
]

[no-multiple-consecutive-spaces]
allow-sentence-double-space = true # "French" sentence spacing for Emacs goodness

[strong-style]
style = "asterisk" # opinionated
